export const snsPostList = [
  {
    id: "2h_001",
    type: "rumor", // "rumor","useful","official","personal","other"
    timeSlot: "2h", // "2h","4h","6h","8h","10h" 災害発生からの時間
    iconUrl: "path/to/icon.png", // とりあえず未実装
    username: "バズジャンキー",
    userId: "@buzz__junkie",
    text: "🚨地震やばすぎて草 無事バズりました🫡（動画つき）",
  },
  {
    id: "2h_002",
    type: "personal",
    timeSlot: "2h",
    iconUrl: "path/to/icon.png",
    username: "白丸🚃",
    userId: "@shiromaru_train",
    text: "乗ってた副都心線止まった……ドア開かない。誰か情報ください；；",
  },
  {
    id: "2h_003",
    type: "rumor",
    timeSlot: "2h",
    iconUrl: "path/to/icon.png",
    username: "バズバズニュース🐯",
    userId: "@buzz_buzz_news",
    text: "渋谷の地下街でガス漏れ→爆発ってまじ！？今は近づかない方がいいってDM来たけど……これほんとにヤバいやつかも #地震 #拡散希望",
  },
  {
    id: "2h_004",
    type: "personal",
    timeSlot: "2h",
    iconUrl: "path/to/icon.png",
    username: "タロヲ",
    userId: "@Taro_0v0",
    text: "職場のビル停電した。しかもWi-Fiも死んでる。詰みました。",
  },
  {
    id: "2h_005",
    type: "useful",
    timeSlot: "2h",
    iconUrl: "path/to/icon.png",
    username: "ハジメチューブ📷",
    userId: "@HajimeTube",
    text: "外にいる人ほんと気をつけて！どこ行っても混んでるけど、安全優先で💦",
  },
  {
    id: "2h_006",
    type: "usefUl",
    timeSlot: "2h",
    iconUrl: "path/to/icon.png",
    username: "サバイバル勢🌪️",
    userId: "@survival_guy",
    text: "道玄坂のファミマ完全にカオス。商品奪い合いでケンカ始まってる。もはや治安崩壊してる。",
  },
  {
    id: "2h_007",
    type: "rumor",
    timeSlot: "2h",
    iconUrl: "path/to/icon.png",
    username: "ネット探偵🕵️‍♂️",
    userId: "@net_tantei",
    text: "【注意】今流れてる“渋谷ガス爆発”は嘘。信じるな！拡散希望。",
  },
  {
    id: "2h_008",
    type: "rumor",
    timeSlot: "2h",
    iconUrl: "path/to/icon.png",
    username: "匿名⚠️",
    userId: "@anonymous_warning",
    text: "都内全域で停電、しかも復旧の見込みなしって聞いたけどマジか？情報ください！",
  },
  {
    id: "2h_009",
    type: "rumor",
    timeSlot: "2h",
    iconUrl: "path/to/icon.png",
    username: "裏ニュース速報",
    userId: "@ura_news",
    text: "誰か知ってる？渋谷で地震の後に爆破予告あったらしいけど。これデマ？怖すぎる……",
  },
  {
    id: "2h_010",
    type: "personal",
    timeSlot: "2h",
    iconUrl: "path/to/icon.png",
    username: "ビル管理人🛠️",
    userId: "@building_manager",
    text: "職場のビル、エレベーター停止中。階段も混んでるし動きづらい……早く復旧してほしい。",
  },
  {
    id: "4h_001",
    type: "personal",
    timeSlot: "4h",
    iconUrl: "path/to/icon.png",
    username: "もも🍑",
    userId: "@momom_0823",
    text: "渋谷駅、地下鉄ずっと止まってる😵‍💫 スタバで充電しよかな……どこ空いてる？💦",
  },
  {
    id: "4h_002",
    type: "rumor",
    timeSlot: "4h",
    iconUrl: "path/to/icon.png",
    username: "せなぴ👀",
    userId: "@senapi_room",
    text: "予知で有名な華先生が、渋谷の高層ビル、このあと余震で全部崩れるって見たらしい…！渋谷居る人やばいよ逃げて！",
  },
  {
    id: "4h_003",
    type: "useful",
    timeSlot: "4h",
    iconUrl: "path/to/icon.png",
    username: "蒼介🏫",
    userId: "@sosuke_aogaku",
    text: "青学、一時避難受け入れてくれてるけど、もう定員ギリ。早めの行動おすすめします🙏",
  },
  {
    id: "4h_004",
    type: "rumor",
    timeSlot: "4h",
    iconUrl: "path/to/icon.png",
    username: "世界終焉論者🌍",
    userId: "@sekai_syuuen",
    text: "これ地震じゃないって言ってる人いるんだけど。渋谷の地下になんか隠してたのが爆発した説、わりと信じてる。",
  },
  {
    id: "4h_005",
    type: "official",
    timeSlot: "4h",
    iconUrl: "path/to/icon.png",
    username: "渋谷区防災【公式】",
    userId: "@shibuya_official",
    text: "【公式】緊急避難の際は「➡」マークのグラフィティをたどってください。道案内になります。",
  },
  {
    id: "4h_006",
    type: "personal",
    timeSlot: "4h",
    iconUrl: "path/to/icon.png",
    username: "しおり🥤",
    userId: "@shiori_drinklove",
    text: "とりあえずドンキで水買ったけど、地獄のような混み具合だった……パンはもう売り切れ；；",
  },
  {
    id: "4h_007",
    type: "useful",
    timeSlot: "4h",
    iconUrl: "path/to/icon.png",
    username: "渋谷NOW📡",
    userId: "@shibuya_now",
    text: "【情報提供】公園通りの公衆トイレはまだ使えるっぽい。簡易トイレの場所もマップでまとめ中！ #渋谷地震",
  },
  {
    id: "4h_008",
    type: "rumor",
    timeSlot: "4h",
    iconUrl: "path/to/icon.png",
    username: "都市伝説くん🌀",
    userId: "@urban_legend_boy",
    text: "渋谷のタワレコに閉じ込められてるって人、全然電波届かないらしい。電磁波攻撃説濃厚じゃね？",
  },
  {
    id: "4h_009",
    type: "personal",
    timeSlot: "4h",
    iconUrl: "path/to/icon.png",
    username: "はるの🌼",
    userId: "@haruno_spring",
    text: "小学生の弟とはぐれました……センター街の交番行ったけど混んでて対応追いついてない感じでした。",
  },
  {
    id: "4h_010",
    type: "official",
    timeSlot: "4h",
    iconUrl: "path/to/icon.png",
    username: "東京都防災【公式】",
    userId: "@tokyo_bousai",
    text: "【災害情報】現在、首都圏の一部エリアで停電・通信障害が発生中。復旧作業を進めています。",
  },
];
