export const snsPostList = [
  {
    id: "2h_001",
    type: "rumor", // "rumor","useful","official","personal","other"
    timeSlot: "2h", // "2h","4h","6h","8h","10h" 災害発生からの時間
    iconUrl: "path/to/icon.png", // とりあえず未実装
    userName: "バズジャンキー",
    userId: "@buzz__junkie",
    text: "🚨地震やばすぎて草 無事バズりました🫡（動画つき）",
  },
  {
    id: "2h_002",
    type: "personal",
    timeSlot: "2h",
    iconUrl: "path/to/icon.png",
    userName: "白丸🚃",
    userId: "@shiromaru_train",
    text: "乗ってた副都心線止まった……ドア開かない。誰か情報ください；；",
  },
  {
    id: "2h_003",
    type: "rumor",
    timeSlot: "2h",
    iconUrl: "path/to/icon.png",
    userName: "バズバズニュース🐯",
    userId: "@buzz_buzz_news",
    text: "渋谷の地下街でガス漏れ→爆発ってまじ！？今は近づかない方がいいってDM来たけど……これほんとにヤバいやつかも #地震 #拡散希望",
  },
  {
    id: "2h_004",
    type: "personal",
    timeSlot: "2h",
    iconUrl: "path/to/icon.png",
    userName: "タロヲ",
    userId: "@Taro_0v0",
    text: "職場のビル停電した。しかもWi-Fiも死んでる。詰みました。",
  },
  {
    id: "2h_005",
    type: "useful",
    timeSlot: "2h",
    iconUrl: "path/to/icon.png",
    userName: "ハジメチューブ📷",
    userId: "@HajimeTube",
    text: "外にいる人ほんと気をつけて！どこ行っても混んでるけど、安全優先で💦",
  },
  {
    id: "2h_006",
    type: "useful",
    timeSlot: "2h",
    iconUrl: "path/to/icon.png",
    userName: "サバイバル勢🌪️",
    userId: "@survival_guy",
    text: "道玄坂のファミマ完全にカオス。商品奪い合いでケンカ始まってる。もはや治安崩壊してる。",
  },
  {
    id: "2h_007",
    type: "rumor",
    timeSlot: "2h",
    iconUrl: "path/to/icon.png",
    userName: "ネット探偵🕵️‍♂️",
    userId: "@net_tantei",
    text: "【注意】今流れてる“渋谷ガス爆発”は嘘。信じるな！拡散希望。",
  },
  {
    id: "2h_008",
    type: "rumor",
    timeSlot: "2h",
    iconUrl: "path/to/icon.png",
    userName: "匿名⚠️",
    userId: "@anonymous_warning",
    text: "都内全域で停電、しかも復旧の見込みなしって聞いたけどマジか？情報ください！",
  },
  {
    id: "2h_009",
    type: "rumor",
    timeSlot: "2h",
    iconUrl: "path/to/icon.png",
    userName: "裏ニュース速報",
    userId: "@ura_news",
    text: "誰か知ってる？渋谷で地震の後に爆破予告あったらしいけど。これデマ？怖すぎる……",
  },
  {
    id: "2h_010",
    type: "personal",
    timeSlot: "2h",
    iconUrl: "path/to/icon.png",
    userName: "ビル管理人🛠️",
    userId: "@building_manager",
    text: "職場のビル、エレベーター停止中。階段も混んでるし動きづらい……早く復旧してほしい。",
  },
  {
    id: "4h_001",
    type: "personal",
    timeSlot: "4h",
    iconUrl: "path/to/icon.png",
    userName: "もも🍑",
    userId: "@momom_0823",
    text: "渋谷駅、地下鉄ずっと止まってる😵‍💫 スタバで充電しよかな……どこ空いてる？💦",
  },
  {
    id: "4h_002",
    type: "rumor",
    timeSlot: "4h",
    iconUrl: "path/to/icon.png",
    userName: "せなぴ👀",
    userId: "@senapi_room",
    text: "予知で有名な華先生が、渋谷の高層ビル、このあと余震で全部崩れるって見たらしい…！渋谷居る人やばいよ逃げて！",
  },
  {
    id: "4h_003",
    type: "useful",
    timeSlot: "4h",
    iconUrl: "path/to/icon.png",
    userName: "蒼介🏫",
    userId: "@sosuke_aogaku",
    text: "青学、一時避難受け入れてくれてるけど、もう定員ギリ。早めの行動おすすめします🙏",
  },
  {
    id: "4h_004",
    type: "rumor",
    timeSlot: "4h",
    iconUrl: "path/to/icon.png",
    userName: "世界終焉論者🌍",
    userId: "@sekai_syuuen",
    text: "これ地震じゃないって言ってる人いるんだけど。渋谷の地下になんか隠してたのが爆発した説、わりと信じてる。",
  },
  {
    id: "4h_005",
    type: "official",
    timeSlot: "4h",
    iconUrl: "path/to/icon.png",
    userName: "渋谷区防災【公式】",
    userId: "@shibuya_official",
    text: "【公式】緊急避難の際は「➡」マークのグラフィティをたどってください。道案内になります。",
  },
  {
    id: "4h_006",
    type: "personal",
    timeSlot: "4h",
    iconUrl: "path/to/icon.png",
    userName: "しおり🥤",
    userId: "@shiori_drinklove",
    text: "とりあえずドンキで水買ったけど、地獄のような混み具合だった……パンはもう売り切れ；；",
  },
  {
    id: "4h_007",
    type: "useful",
    timeSlot: "4h",
    iconUrl: "path/to/icon.png",
    userName: "渋谷NOW📡",
    userId: "@shibuya_now",
    text: "【情報提供】公園通りの公衆トイレはまだ使えるっぽい。簡易トイレの場所もマップでまとめ中！ #渋谷地震",
  },
  {
    id: "4h_008",
    type: "rumor",
    timeSlot: "4h",
    iconUrl: "path/to/icon.png",
    userName: "都市伝説くん🌀",
    userId: "@urban_legend_boy",
    text: "渋谷のタワレコに閉じ込められてるって人、全然電波届かないらしい。電磁波攻撃説濃厚じゃね？",
  },
  {
    id: "4h_009",
    type: "personal",
    timeSlot: "4h",
    iconUrl: "path/to/icon.png",
    userName: "はるの🌼",
    userId: "@haruno_spring",
    text: "小学生の弟とはぐれました……センター街の交番行ったけど混んでて対応追いついてない感じでした。",
  },
  {
    id: "4h_010",
    type: "official",
    timeSlot: "4h",
    iconUrl: "path/to/icon.png",
    userName: "東京都防災【公式】",
    userId: "@tokyo_bousai",
    text: "【災害情報】現在、首都圏の一部エリアで停電・通信障害が発生中。復旧作業を進めています。",
  },
  {
    id: "6h_001",
    type: "personal",
    timeSlot: "6h",
    iconUrl: "path/to/icon.png",
    userName: "ゆうき🚶‍♂️",
    userId: "@yuuki_walker",
    text: "やっと外に出られたけど、渋谷はまだ混乱してる。気をつけて移動しよう。",
  },
  {
    id: "6h_002",
    type: "useful",
    timeSlot: "6h",
    iconUrl: "path/to/icon.png",
    userName: "防災のミカ👩‍🚒",
    userId: "@bosai_mika",
    text: "余震に備えて安全な場所に待機しよう。無理に移動は控えてね。",
  },
  {
    id: "6h_003",
    type: "rumor",
    timeSlot: "6h",
    iconUrl: "path/to/icon.png",
    userName: "都市伝説探偵🕵️‍♂️",
    userId: "@legend_detective",
    text: "また大きな地震来るって話、信じる？SNSで色々流れてるけど真相は不明だよね。",
  },
  {
    id: "6h_004",
    type: "official",
    timeSlot: "6h",
    iconUrl: "path/to/icon.png",
    userName: "渋谷区防災【公式】",
    userId: "@shibuya_official",
    text: "【公式】避難所はまだ空きがあります。体調が悪い方は速やかに避難をお願いします。",
  },
  {
    id: "6h_005",
    type: "personal",
    timeSlot: "6h",
    iconUrl: "path/to/icon.png",
    userName: "あきら⚡",
    userId: "@akira_lightning",
    text: "電車はまだ動いてないけど、歩いて帰る人多いね。みんな無事でいてほしい。",
  },
  {
    id: "6h_006",
    type: "useful",
    timeSlot: "6h",
    iconUrl: "path/to/icon.png",
    userName: "情報局📡",
    userId: "@info_station",
    text: "水や食料の配給場所を地図にまとめました。必要な人はチェックしてね。",
  },
  {
    id: "6h_007",
    type: "rumor",
    timeSlot: "6h",
    iconUrl: "path/to/icon.png",
    userName: "噂好き🐦",
    userId: "@gossip_bird",
    text: "近所のスーパーで暴動が起きてるって聞いたけど本当かな？怖い…",
  },
  {
    id: "6h_008",
    type: "personal",
    timeSlot: "6h",
    iconUrl: "path/to/icon.png",
    userName: "はるか🌸",
    userId: "@haruka_spring",
    text: "友達と連絡取れなくて不安だけど、みんな無事ならいいな。",
  },
  {
    id: "6h_009",
    type: "official",
    timeSlot: "6h",
    iconUrl: "path/to/icon.png",
    userName: "東京都防災【公式】",
    userId: "@tokyo_bousai",
    text: "【公式】停電は一部復旧しましたが、まだ注意が必要です。最新情報を確認してください。",
  },
  {
    id: "6h_010",
    type: "useful",
    timeSlot: "6h",
    iconUrl: "path/to/icon.png",
    userName: "ボランティア募集中🙋‍♂️",
    userId: "@volunteer_tokyo",
    text: "支援物資の仕分け手伝ってくれる人募集中！興味ある人はDMください！",
  },
  {
    id: "8h_001",
    type: "personal",
    timeSlot: "8h",
    iconUrl: "path/to/icon.png",
    userName: "みさと🌿",
    userId: "@misato_safe",
    text: "ようやく避難所に着いた。水と食料があってひとまず安心したけど、まだ先が読めないなぁ。",
  },
  {
    id: "8h_002",
    type: "useful",
    timeSlot: "8h",
    iconUrl: "path/to/icon.png",
    userName: "区民館スタッフ🏢",
    userId: "@community_center",
    text: "区民館は今、支援物資の配布拠点になっています。必要な方はぜひお越しください。",
  },
  {
    id: "8h_003",
    type: "rumor",
    timeSlot: "8h",
    iconUrl: "path/to/icon.png",
    userName: "噂好き🐦",
    userId: "@gossip_bird",
    text: "近所の避難所で暴動が起きてるって話だけど、本当？信じていいのかな…",
  },
  {
    id: "8h_004",
    type: "official",
    timeSlot: "8h",
    iconUrl: "path/to/icon.png",
    userName: "渋谷区防災【公式】",
    userId: "@shibuya_official",
    text: "【公式】避難所の混雑緩和のため、一時避難場所の利用もご検討ください。",
  },
  {
    id: "8h_005",
    type: "personal",
    timeSlot: "8h",
    iconUrl: "path/to/icon.png",
    userName: "ケンジ🚶‍♂️",
    userId: "@kenji_walk",
    text: "やっと学校の避難場所に到着。みんな無事そうでよかった。でもまだまだ油断禁物だな。",
  },
  {
    id: "8h_006",
    type: "personal",
    timeSlot: "8h",
    iconUrl: "path/to/icon.png",
    userName: "りえ🌸",
    userId: "@rie_chill",
    text: "こんな時でもいつも通りスタバ来ちゃった。平和ボケしてる自分が怖い（笑）",
  },
  {
    id: "8h_007",
    type: "useful",
    timeSlot: "8h",
    iconUrl: "path/to/icon.png",
    userName: "サポート隊🚑",
    userId: "@support_team",
    text: "支援施設でボランティア募集してます。できる範囲でぜひご協力をお願いします！",
  },
  {
    id: "8h_008",
    type: "rumor",
    timeSlot: "8h",
    iconUrl: "path/to/icon.png",
    userName: "都市伝説探偵🕵️‍♂️",
    userId: "@legend_detective",
    text: "また大きな余震が来るって聞いたけど、マジで怖い。みんな気をつけて！",
  },
  {
    id: "8h_009",
    type: "personal",
    timeSlot: "8h",
    iconUrl: "path/to/icon.png",
    userName: "まゆ🌷",
    userId: "@mayu_peace",
    text: "避難所で新しい友達ができた。みんなで助け合って乗り切ろうね。",
  },
  {
    id: "8h_010",
    type: "personal",
    timeSlot: "8h",
    iconUrl: "path/to/icon.png",
    userName: "タカシ🍣",
    userId: "@takashi_sushi",
    text: "普通に寿司食べてる。なんか周りがバタバタしてるけど、自分はまだ日常モードｗ",
  },
  {
    id: "10h_001",
    type: "personal",
    timeSlot: "10h",
    iconUrl: "path/to/icon.png",
    userName: "ユウカ🌙",
    userId: "@yuuka_sleepy",
    text: "眠すぎてもう限界……避難所でちょっと仮眠してるけど、やっぱり家が恋しいなあ。",
  },
  {
    id: "10h_002",
    type: "useful",
    timeSlot: "10h",
    iconUrl: "path/to/icon.png",
    userName: "支援スタッフ🚑",
    userId: "@support_staff",
    text: "充電スポットはかなり混雑しています。時間をずらしての利用をおすすめします。",
  },
  {
    id: "10h_003",
    type: "personal",
    timeSlot: "10h",
    iconUrl: "path/to/icon.png",
    userName: "タケシ🍙",
    userId: "@takeshi_hungry",
    text: "お腹ペコペコ……施設の食料もそろそろ尽きそう。誰か差し入れしてくれないかな…",
  },
  {
    id: "10h_004",
    type: "rumor",
    timeSlot: "10h",
    iconUrl: "path/to/icon.png",
    userName: "怪情報屋👹",
    userId: "@kaijouhou",
    text: "渋谷駅の地下に秘密の非常用トンネルがあるらしい…本当にあるのか？ #都市伝説",
  },
  {
    id: "10h_005",
    type: "official",
    timeSlot: "10h",
    iconUrl: "path/to/icon.png",
    userName: "渋谷区防災【公式】",
    userId: "@shibuya_official",
    text: "【公式】避難所の状況は日々変動しています。最新情報は公式サイトでご確認ください。",
  },
  {
    id: "10h_006",
    type: "personal",
    timeSlot: "10h",
    iconUrl: "path/to/icon.png",
    userName: "ナオキ🚶‍♂️",
    userId: "@naoki_chill",
    text: "まだ家に帰れないけど、ここ数時間は少し落ち着いてきたかな。みんな頑張ってる。",
  },
  {
    id: "10h_007",
    type: "personal",
    timeSlot: "10h",
    iconUrl: "path/to/icon.png",
    userName: "ミホ🌈",
    userId: "@miho_everyday",
    text: "普通に電車乗ってる人もいるみたい。まだまだ自分は日常モードだなあ…大丈夫かな？",
  },
  {
    id: "10h_008",
    type: "useful",
    timeSlot: "10h",
    iconUrl: "path/to/icon.png",
    userName: "医療チーム🏥",
    userId: "@medical_team",
    text: "混雑している避難所もあります。体調不良の方は早めに医療機関へご相談ください。",
  },
  {
    id: "10h_009",
    type: "rumor",
    timeSlot: "10h",
    iconUrl: "path/to/icon.png",
    userName: "噂好き🐦",
    userId: "@gossip_bird",
    text: "近くの避難所で不審者が出没してるって話、みんな気をつけて！本当ならヤバい…",
  },
  {
    id: "10h_010",
    type: "personal",
    timeSlot: "10h",
    iconUrl: "path/to/icon.png",
    userName: "ケイコ☕️",
    userId: "@keiko_relax",
    text: "コーヒー飲みながら避難所でまったり。まだまだ長期戦だけど、焦らず行こう！",
  },
];
